Add collapsable items in OutlinePanel
theatre-js/theatre pull request #255
Opened 2022-07-08 19:01 UTC by colelawrence

2022-08-08 18:17 UTC, vezwork requested changes
Awesome. Looks great apart from two requested changes.

2022-08-08 18:17 UTC, vezwork commented on theatre/studio/src/panels/OutlinePanel/BaseItem.tsx
> +  transform: rotate(${(props) => (props.isOpen ? '0deg' : '-90deg')});
perf: pull this out into a style prop so that styled does not recompute the css when this changes.

2022-08-08 18:17 UTC, vezwork commented on theatre/studio/src/panels/OutlinePanel/BaseItem.tsx
> +  display: ${(props) => (props.show ? 'block' : 'none')};
perf: pull out to a style prop for same reason as other comment

2022-08-08 18:17 UTC, vezwork commented on theatre/studio/src/panels/OutlinePanel/BaseItem.tsx
> +  const [isOpen, setIsOpen] = useState(true)
I think ideally this would be stored in the studio data. Happy to merge this PR and add that in follow-up PR though.

2022-12-27 21:46 UTC, clementroche commented
Yo, this still needs changes before to be merged ?

2022-12-29 18:56 UTC, tomorrowevening commented
Additional changes in @clementroche's PR https://github.com/theatre-js/theatre/pull/367, can you merge those in? 😬

2022-12-31 22:27 UTC, AriaMinaei commented
Closing in favor of #367

2022-12-31 22:27 UTC, closed without merging