refactor: Playground items now don't load studio in iframes
theatre-js/theatre pull request #277
Opened 2022-08-05 17:33 UTC by colelawrence

* Greatly improves the load time of the playground

2022-08-05 17:43 UTC, colelawrence commented
# Squash and merge is good

2022-08-08 12:07 UTC, vezwork requested changes

2022-08-08 12:07 UTC, vezwork commented on packages/playground/src/common/LazyLoadStudio.tsx
> +      const loadPromise =
See my readability suggestion for the type of `import` above. Also see suggestion to make the scope async so await case be used. This suggestion would simplify this into a single case (ternary operator not necessary) and remove the need for nested callbacks.

2022-08-08 12:07 UTC, vezwork commented on packages/playground/src/common/LazyLoadStudio.tsx
> +}
I like this. Made it easy to think thru the async code.

2022-12-31 22:44 UTC, closed without merging